### ISSUE TITLE
请问这个打卡失败是哪里出了问题呢

### ISSUE THREAD

**Issue by kangyeye** [stevaon/chd-daka#6]
- Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/div"}

**Comment by stevaon** [comment]
谢谢！

kangyeye ***@***.***> 于2022年11月4日周五 08:17写道：

**Comment by stevaon** [comment]
判断是否已过打卡时间点

**Comment by kangyeye** [comment]
cron: '36 22,6 * * *'  这是我设置的cron 您好&nbsp; 6：36是在打卡时间范围内呀
请问还有哪些可能的原因吗&nbsp; 我不太懂 不好意思打扰你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月4日(星期五) 下午4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stevaon/chd-daka] 请问这个打卡失败是哪里出了问题呢 (Issue #6)





 
判断是否已过打卡时间点

**Comment by stevaon** [comment]
github服务器使用的是uTC时间，和北京时间差8个小时，所以如果现在早上7点10分打卡，就得设置成10 23 * * *，这样的话服务器会在北京时间7点10分将打卡任务推到任务队列里面，等待执行就行了，一般1个小时内执行都算正常
